language: java

addons:    
  sonarcloud:
    organization: "fastluca-github"

before_install:
  - if [[ "${TRAVIS_OS_NAME}" == linux ]]; then export DISPLAY=:99.0; sh -e /etc/init.d/xvfb start; fi
  
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar