language: java

addons:
  sonarcloud:
    organization: "fastluca-github"

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent coveralls:report install sonar:sonar
#after_success:
#  - mvn clean test jacoco:report coveralls:report